# -*- coding: utf-8 -*-
# Part of SGC TECH AI. See LICENSE file for full copyright and licensing details.
# Copyright (c) 2026 SGC TECH AI (https://sgctech.ai)

import base64
import json
import zlib

from odoo import api, fields, models, _

import logging

_logger = logging.getLogger(__name__)

# Re-use the same selection as the wizard so the audit record can be filtered
# consistently with the wizard that generated it. Kept as a local copy (not
# imported) so this module remains self-contained - touching the wizard
# selection will not silently widen this model's audit domain.
REPORT_TYPE_SELECTION = [
    ("balance_sheet", "Balance Sheet"),
    ("profit_loss", "Profit & Loss"),
    ("cash_flow", "Cash Flow Statement"),
    ("trial_balance", "Trial Balance"),
    ("general_ledger", "General Ledger"),
    ("partner_ledger", "Partner Ledger"),
    ("aged_receivable", "Aged Receivable"),
    ("aged_payable", "Aged Payable"),
    ("tax_report", "Tax Report"),
]

TARGET_MOVE_SELECTION = [
    ("posted", "All Posted Entries"),
    ("all", "All Entries"),
    ("draft", "Draft Entries Only"),
]


class SgcDfrReportLog(models.Model):
    """Audit trail entry for every SGC Dynamic Financial Report generation.

    Created automatically by the wizard / scheduled-runner after a report is
    computed. Stores a snapshot of the parameters that produced the report,
    a textual summary of the financial data, and a compressed JSON payload
    of the engine's raw ``data`` dict so the same report can be reproduced
    or audited later even if the underlying accounting moves have changed.

    The model is **append-only** by design: users with `user` group can only
    read; managers and admins can create. No UI updates / unlinks are
    exposed (security CSV).
    """

    _name = "sgc.dfr.report.log"
    _description = "SGC DFR Report Audit Log"
    _order = "generated_at DESC, id DESC"
    _rec_name = "display_name"

    # ── Source / context ──────────────────────────────────────────────
    wizard_id = fields.Reference(
        selection=[("sgc.financial.report.wizard", "Source Wizard")],
        string="Source Wizard",
        readonly=True,
        index=True,
        help="Transient wizard record that produced this report, "
             "if it originated from a manual UI run.  Stored as a "
             "Reference (not Many2one) because the target is a "
             "TransientModel, which Odoo 19 forbids as Many2one target.",
    )
    scheduled_report_id = fields.Many2one(
        comodel_name="sgc.dfr.scheduled.report",
        string="Scheduled Report",
        readonly=True,
        ondelete="set null",
        index=True,
        help="Scheduled-report definition that triggered this run, "
             "if it was produced by the scheduler.",
    )

    # ── Report parameters (mirrored from the wizard) ──────────────────
    report_type = fields.Selection(
        selection=REPORT_TYPE_SELECTION,
        string="Report Type",
        required=True,
        index=True,
    )
    company_id = fields.Many2one(
        comodel_name="res.company",
        string="Company",
        required=True,
        index=True,
    )
    date_from = fields.Date(string="Start Date", required=True)
    date_to = fields.Date(string="End Date", required=True)

    comparison_enabled = fields.Boolean(string="Comparison Enabled")
    comparison_period = fields.Char(
        string="Comparison Period",
        size=64,
        help="Human-readable label of the comparison window, e.g. "
             "'2025-01-01..2025-12-31'.",
    )

    account_ids = fields.Text(
        string="Accounts",
        help="Comma-separated list of account IDs / codes that were "
             "filtered into the report.",
    )
    partner_ids = fields.Text(
        string="Partners",
        help="Comma-separated list of partner IDs that were filtered.",
    )
    target_move = fields.Selection(
        selection=TARGET_MOVE_SELECTION,
        string="Target Moves",
    )
    analytic_account_ids = fields.Text(
        string="Analytic Accounts",
        help="Comma-separated list of analytic account IDs.",
    )
    journal_ids = fields.Text(
        string="Journals",
        help="Comma-separated list of journal IDs.",
    )

    # Boolean UI flags stored as a JSON dict so new flags can be added
    # without schema migrations. Example: {"show_hierarchy": true,
    # "show_zero_balance": false, "hide_parent_hierarchy": false,
    # "tax_grid": false}.
    options = fields.Json(
        string="Display Options",
        help="JSON snapshot of the boolean display flags used at "
             "generation time.",
    )

    # ── Audit metadata ────────────────────────────────────────────────
    generated_by = fields.Many2one(
        comodel_name="res.users",
        string="Generated By",
        readonly=True,
        default=lambda self: self.env.user,
        index=True,
    )
    generated_at = fields.Datetime(
        string="Generated At",
        required=True,
        readonly=True,
        default=fields.Datetime.now,
        index=True,
    )
    source = fields.Selection(
        selection=[
            ("manual", "Manual (UI)"),
            ("scheduled", "Scheduled (Cron)"),
            ("preview", "Preview / Test"),
        ],
        string="Source",
        default="manual",
        required=True,
        index=True,
    )

    # ── Result snapshot ───────────────────────────────────────────────
    result_summary = fields.Text(
        string="Result Summary",
        help="First 500 characters of the rendered HTML, stripped of "
             "tags. Used for quick scanning in the audit log tree view.",
    )
    report_data_snapshot = fields.Binary(
        string="Report Data Snapshot",
        attachment=True,
        help="zlib-compressed JSON payload of the engine's result.data "
             "dict. Allows reconstructing the exact figures that were "
             "produced at generation time, even after the underlying "
             "accounting moves change.",
    )
    report_data_size = fields.Integer(
        string="Snapshot Size (bytes)",
        readonly=True,
        help="Uncompressed size of the snapshot JSON, stored for "
             "housekeeping decisions (archive / purge).",
    )

    # ── Display helper ────────────────────────────────────────────────
    display_name = fields.Char(
        string="Display Name",
        compute="_compute_display_name",
        store=True,
    )

    # ── Computed display name ────────────────────────────────────────
    @api.depends("report_type", "company_id", "date_from", "date_to", "generated_at")
    def _compute_display_name(self):
        for rec in self:
            rtype = dict(REPORT_TYPE_SELECTION).get(rec.report_type, rec.report_type)
            company = rec.company_id.name or ""
            dfrom = fields.Date.to_string(rec.date_from) if rec.date_from else ""
            dto = fields.Date.to_string(rec.date_to) if rec.date_to else ""
            when = fields.Datetime.to_string(rec.generated_at) if rec.generated_at else ""
            rec.display_name = f"[{rtype}] {company} {dfrom}..{dto} @ {when}"

    # ── Snapshot helpers ──────────────────────────────────────────────
    @api.model
    def _compress_snapshot(self, data):
        """Compress a JSON-serialisable ``data`` dict into a base64 binary.

        Returns (binary_value, uncompressed_byte_size).
        """
        if data is None:
            return False, 0
        raw = json.dumps(data, default=str, ensure_ascii=False).encode("utf-8")
        compressed = zlib.compress(raw, level=6)
        return base64.b64encode(compressed), len(raw)

    @api.model
    def _decompress_snapshot(self, binary_value):
        """Inverse of :meth:`_compress_snapshot`. Returns the original dict."""
        if not binary_value:
            return {}
        compressed = base64.b64decode(binary_value)
        raw = zlib.decompress(compressed)
        return json.loads(raw.decode("utf-8"))

    # ── Factory: create from wizard + engine result ───────────────────
    @api.model
    def create_from_wizard(self, wizard, result, source="manual", scheduled_report=None):
        """Build a new audit-trail row from a wizard + engine ``result`` dict.

        Args:
            wizard: ``sgc.financial.report.wizard`` recordset (size 1).
            result: dict returned by the engine ``_generate_report``;
                    must have at least ``html`` and optionally ``data``.
            source: one of the ``source`` selection values.
            scheduled_report: optional ``sgc.dfr.scheduled.report`` recordset.

        Returns:
            ``sgc.dfr.report.log`` recordset (size 1).
        """
        html = result.get("html", "") or ""
        # Strip tags for a flat-text summary usable in the tree view.
        summary = self._html_to_text(html)[:500]

        snapshot_bin, snapshot_size = self._compress_snapshot(result.get("data"))

        comparison_period = False
        if wizard.enable_comparison and wizard.comparison_date_from and wizard.comparison_date_to:
            comparison_period = "{}..{}".format(
                fields.Date.to_string(wizard.comparison_date_from),
                fields.Date.to_string(wizard.comparison_date_to),
            )

        vals = {
            "wizard_id": "sgc.financial.report.wizard,{}".format(wizard.id),
            "scheduled_report_id": scheduled_report and scheduled_report.id or False,
            "report_type": wizard.report_type,
            "company_id": wizard.company_id.id,
            "date_from": wizard.date_from,
            "date_to": wizard.date_to,
            "comparison_enabled": bool(wizard.enable_comparison),
            "comparison_period": comparison_period,
            "account_ids": self._format_id_list(wizard.account_ids),
            "partner_ids": self._format_id_list(wizard.partner_ids),
            "target_move": wizard.target_move,
            "analytic_account_ids": self._format_id_list(wizard.analytic_account_ids),
            "journal_ids": self._format_id_list(wizard.journal_ids),
            "options": {
                "show_hierarchy": bool(wizard.show_hierarchy),
                "show_zero_balance": bool(wizard.show_zero_balance),
                "hide_parent_hierarchy": bool(wizard.hide_parent_hierarchy),
                "tax_grid": bool(wizard.tax_grid),
            },
            "generated_by": self.env.user.id,
            "generated_at": fields.Datetime.now(),
            "source": source,
            "result_summary": summary,
            "report_data_snapshot": snapshot_bin,
            "report_data_size": snapshot_size,
        }
        return self.create(vals)

    # ── Helpers ───────────────────────────────────────────────────────
    @staticmethod
    def _format_id_list(recordset):
        """Return a comma-separated string of IDs from a recordset or False."""
        if not recordset:
            return False
        return ",".join(str(r.id) for r in recordset)

    @staticmethod
    def _html_to_text(html):
        """Cheap HTML tag stripper for summary text."""
        if not html:
            return ""
        out = []
        in_tag = False
        for ch in html:
            if ch == "<":
                in_tag = True
            elif ch == ">":
                in_tag = False
            elif not in_tag:
                out.append(ch)
        text = "".join(out)
        # Collapse runs of whitespace.
        return " ".join(text.split())
