from . import account_move
from . import agreement_template
from . import certificate_type
from . import commission_line
from . import contract_duration
from . import crm_lead
from . import file_validation_mixin
from . import ir_action
from . import ir_ui_view
from . import maintenance
from . import product_product
from . import property_amenities
from . import property_connectivity
from . import parent_property
from . import payment_schedule
from . import property_details
from . import property_documents
from . import property_specification
from . import property_tag
from . import property_project
from . import property_region
from . import property_res_city
from . import property_sub_project
from . import property_image
from . import property_vendor
from . import property_vendor_commission_line
from . import rent_bill
from . import rent_contract
from . import rent_invoice
from . import res_config
from . import res_partner
from . import sale_contract
from . import sale_contract_installment
from . import sale_inquiry
from . import tenancy_details
from . import rera_form_a
from . import tenancy_inquiry
