#!/usr/bin/env bash
#
# clone_staging.sh
# ----------------
# One-shot bootstrap of the staging stack. Idempotent and safe to re-run.
#
# What it does:
#   1. pg_dump (READ-ONLY) the live demo_presentation_19 DB from the live
#      demo_presentation_db container into a custom-format snapshot.
#   2. Build a staging addons directory that mirrors the live one, EXCEPT the
#      target module, which is checked out as a git worktree on the `develop`
#      branch (so staging always reflects `develop`, while the live checkout
#      stays on `master`).
#   3. Write the staging docker-compose file (separate container names, ports
#      18040/18041, separate volumes, db-filter demo_presentation_19).
#   4. Bring up the staging DB, restore the snapshot into it, then bring up the
#      staging Odoo web process.
#
# It NEVER stops/restarts/writes to the live containers.
#
# Usage: ops/clone_staging.sh [--refresh-db]
#   --refresh-db   Re-dump and re-restore the DB even if a snapshot already
#                  exists (default: reuse an existing snapshot if present).

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

REFRESH_DB=0
for arg in "$@"; do
  case "$arg" in
    --refresh-db) REFRESH_DB=1 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) die "unknown argument: $arg (see --help)" ;;
  esac
done

# --- 0. Sanity ---------------------------------------------------------------
docker inspect "${LIVE_DB_CONTAINER}" >/dev/null 2>&1 \
  || die "live DB container '${LIVE_DB_CONTAINER}' not found; is the live stack up?"

mkdir -p "${STAGING_DIR}"

# --- 1. Dump the live DB (read-only) -----------------------------------------
if [[ -f "${STAGING_DB_DUMP}" && "${REFRESH_DB}" -eq 0 ]]; then
  log "Reusing existing DB snapshot at ${STAGING_DB_DUMP} (pass --refresh-db to re-dump)."
else
  log "Dumping live DB '${DB_NAME}' from '${LIVE_DB_CONTAINER}' (read-only)..."
  # -Fc = custom format (compressed, restorable with pg_restore).
  docker exec "${LIVE_DB_CONTAINER}" \
    pg_dump -U "${DB_USER}" -Fc "${DB_NAME}" > "${STAGING_DB_DUMP}.tmp"
  mv "${STAGING_DB_DUMP}.tmp" "${STAGING_DB_DUMP}"
  log "Snapshot written: $(du -h "${STAGING_DB_DUMP}" | cut -f1)"
fi

# --- 2. Build the staging addons dir -----------------------------------------
log "Mirroring live addons -> staging (excluding ${MODULE})..."
mkdir -p "${STAGING_ADDONS_DIR}"
# rsync -a preserves symlinks/perms; --delete keeps staging in sync on re-run.
# We exclude the target module here and manage it as a git worktree below.
rsync -a --delete \
  --exclude "/${MODULE}" \
  "${LIVE_ADDONS_DIR}/" "${STAGING_ADDONS_DIR}/"

WORKTREE_PATH="${STAGING_ADDONS_DIR}/${MODULE}"
if git -C "${MODULE_DIR}" worktree list --porcelain | grep -q "worktree ${WORKTREE_PATH}$"; then
  log "Worktree already present; fetching latest develop into it..."
  git -C "${WORKTREE_PATH}" checkout develop
  git -C "${WORKTREE_PATH}" reset --hard develop
else
  # Remove any stale non-worktree copy left by a previous rsync run.
  [[ -e "${WORKTREE_PATH}" ]] && rm -rf "${WORKTREE_PATH}"
  log "Creating git worktree for ${MODULE} on 'develop'..."
  git -C "${MODULE_DIR}" worktree prune
  git -C "${MODULE_DIR}" worktree add "${WORKTREE_PATH}" develop
fi

# --- 3. Write the staging compose file ---------------------------------------
log "Writing staging compose file: ${STAGING_COMPOSE}"
cat > "${STAGING_COMPOSE}" <<YAML
# Auto-generated by ops/clone_staging.sh. Do not edit by hand.
# Staging mirror of the live demo_presentation stack.
name: ${STAGING_PROJECT}

services:
  db:
    image: postgres:16
    container_name: ${STAGING_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - staging-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  odoo:
    image: odoo:19.0
    container_name: ${STAGING_ODOO_CONTAINER}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "18040:8069"
      - "18041:8072"
    volumes:
      - ./addons:/mnt/extra-addons:ro
      - staging-odoo:/var/lib/odoo
    environment:
      HOST: db
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
    command: odoo --db_host=db --db_user=${DB_USER} --db_password=${DB_PASSWORD} --addons-path=${ODOO_ADDONS_PATH} --log-level=warn --db-filter=^${DB_NAME}\$
    restart: unless-stopped

volumes:
  staging-db:
  staging-odoo:
YAML

# --- 4. Bring up DB, restore snapshot, then bring up Odoo ---------------------
assert_not_live "${STAGING_DB_CONTAINER}"
log "Starting staging DB..."
${DC} -f "${STAGING_COMPOSE}" -p "${STAGING_PROJECT}" up -d db
wait_for_db "${STAGING_DB_CONTAINER}"

# Restore the snapshot. Drop+recreate the DB for a clean, idempotent restore.
if [[ "${REFRESH_DB}" -eq 1 ]] || ! docker exec "${STAGING_DB_CONTAINER}" \
      psql -U "${DB_USER}" -lqt | cut -d'|' -f1 | grep -qw "${DB_NAME}"; then
  log "Restoring snapshot into staging DB '${DB_NAME}'..."
  docker exec "${STAGING_DB_CONTAINER}" dropdb -U "${DB_USER}" --if-exists "${DB_NAME}"
  docker exec "${STAGING_DB_CONTAINER}" createdb -U "${DB_USER}" "${DB_NAME}"
  # --no-owner: the dump's role grants aren't needed; everything runs as odoo.
  docker exec -i "${STAGING_DB_CONTAINER}" \
    pg_restore -U "${DB_USER}" -d "${DB_NAME}" --no-owner < "${STAGING_DB_DUMP}"
  log "Restore complete."
else
  log "Staging DB '${DB_NAME}' already present; skipping restore (use --refresh-db to force)."
fi

log "Starting staging Odoo..."
assert_not_live "${STAGING_ODOO_CONTAINER}"
${DC} -f "${STAGING_COMPOSE}" -p "${STAGING_PROJECT}" up -d odoo

log "Waiting for staging Odoo HTTP on :18040..."
if wait_for_http 18040; then
  log "Staging is UP: http://localhost:18040/web/login"
else
  log "WARNING: staging HTTP did not respond on :18040 yet. Check: docker logs ${STAGING_ODOO_CONTAINER}"
fi

log "clone_staging.sh done."
