# -*- coding: utf-8 -*-
# Part of SGC UI Brand Palette (standalone, v19.0.2.0.0).
#
# ODOO 19 VERIFIED FACTS (confirmed against the live Odoo 19.0 Community
# image before writing this file — see CHANGES.md for the verification
# log):
#
#   - `res.company` already carries `primary_color` / `secondary_color`
#     (defined in odoo/addons/web/models/res_company.py, exposed on the
#     settings form via `base.document.layout` for PDF/report branding).
#     This module REUSES those two fields rather than duplicating them —
#     a tenant who already set their document brand colors gets a
#     matching backend UI with zero extra configuration.
#   - The only genuinely NEW fields this module adds are the three that
#     `primary_color`/`secondary_color` do not cover: navbar background,
#     navbar text, and an optional link-color override.
#   - CSS variable target `--bs-primary` / `--bs-primary-rgb` /
#     `--bs-secondary` / `--bs-secondary-rgb` / `--bs-link-color` are
#     confirmed generated by Bootstrap 5's `_root.scss` with
#     `$prefix: bs-` (Odoo 19's bundled Bootstrap, verified in
#     odoo/addons/web/static/lib/bootstrap/scss/_variables.scss and
#     _root.scss). Overriding them at `:root` in a later-loaded <style>
#     tag reliably reskins every Bootstrap-driven component (buttons,
#     links, badges, form controls) via CSS cascade — no SCSS
#     recompilation needed, which is what makes this safe per-tenant.
#   - `.o_main_navbar` is confirmed present in
#     odoo/addons/web/static/src/webclient/navbar/navbar.scss, using
#     `background: $o-navbar-background` (a compiled SCSS variable, not
#     a CSS custom property) — overridden here via a direct class rule.
#     The same file confirms `color: var(--NavBar-entry-color, ...)` on
#     `.o_menu_toggle` and sibling entries, which IS a genuine CSS
#     custom property we can safely set.
#
# KNOWN LIMITATION (flagged, not guessed around): Odoo Enterprise's
# AppsBar/left-sidebar component was not present in the Community image
# used to verify this module, so no sidebar-specific selector is
# targeted here. If deployed on Enterprise, the sidebar keeps its
# default look until a human verifies and adds the correct selector —
# do not add one without checking the live DOM/SCSS first.
import re

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

_HEX_COLOR_RE = re.compile(r"^#[0-9A-Fa-f]{6}$")

# Starter defaults shown in a fresh Settings panel — NOT silently
# applied to existing data. A tenant sees these as the pre-filled
# swatch values and can repaint them immediately; they are not an
# assumed brand identity, just a sane out-of-the-box starting point.
DEFAULT_NAVBAR_BG = "#1B2A4A"
DEFAULT_NAVBAR_TEXT = "#FFFFFF"


class ResCompany(models.Model):
    _inherit = "res.company"

    brand_navbar_bg_color = fields.Char(
        string="Navbar background",
        default=DEFAULT_NAVBAR_BG,
        help="Top navbar background colour for this company's backend "
             "UI. Hex format, e.g. #1B2A4A.",
    )
    brand_navbar_text_color = fields.Char(
        string="Navbar text",
        default=DEFAULT_NAVBAR_TEXT,
        help="Top navbar icon/text colour for this company's backend UI.",
    )
    brand_link_color = fields.Char(
        string="Link colour (override)",
        help="Optional — overrides the default link colour. Leave blank "
             "to use the Primary colour (set below, under Document "
             "Layout) for links as well.",
    )

    @api.constrains(
        "brand_navbar_bg_color", "brand_navbar_text_color",
        "brand_link_color",
    )
    def _check_brand_colors_are_hex(self):
        for company in self:
            for fname in (
                "brand_navbar_bg_color", "brand_navbar_text_color",
                "brand_link_color",
            ):
                value = company[fname]
                if value and not _HEX_COLOR_RE.match(value):
                    raise ValidationError(_(
                        "%(field)s must be a hex colour like #1B2A4A "
                        "(got %(value)r).",
                        field=self._fields[fname].string, value=value,
                    ))

    def action_reset_brand_defaults(self):
        """Reset this company's UI brand fields to the module defaults.
        Does NOT touch `primary_color`/`secondary_color` — those belong
        to the core document-layout feature and have their own reset
        path (the "Reset to logo colours" button already provided by
        Odoo's Document Layout configurator).
        """
        for company in self:
            company.write({
                "brand_navbar_bg_color": DEFAULT_NAVBAR_BG,
                "brand_navbar_text_color": DEFAULT_NAVBAR_TEXT,
                "brand_link_color": False,
            })

    @staticmethod
    def _hex_to_rgb_triplet(hex_color):
        """`#1B2A4A` -> `27,42,74` (Bootstrap's `--bs-*-rgb` format)."""
        hex_color = hex_color.lstrip("#")
        return ",".join(str(int(hex_color[i:i + 2], 16)) for i in (0, 2, 4))

    def _get_sgc_brand_css(self):
        """Build the per-company CSS override block.

        Every property is emitted ONLY when the underlying value is a
        valid hex colour — an unset or invalid field is skipped
        entirely rather than falling back to a silently-invented
        colour, so a half-configured tenant never ships broken CSS.
        """
        self.ensure_one()
        root_lines = []
        navbar_lines = []

        primary = self.primary_color if _HEX_COLOR_RE.match(
            self.primary_color or "") else None
        secondary = self.secondary_color if _HEX_COLOR_RE.match(
            self.secondary_color or "") else None
        link = self.brand_link_color if _HEX_COLOR_RE.match(
            self.brand_link_color or "") else primary
        navbar_bg = self.brand_navbar_bg_color if _HEX_COLOR_RE.match(
            self.brand_navbar_bg_color or "") else None
        navbar_text = self.brand_navbar_text_color if _HEX_COLOR_RE.match(
            self.brand_navbar_text_color or "") else None

        if primary:
            root_lines.append(f"--bs-primary: {primary};")
            root_lines.append(
                f"--bs-primary-rgb: {self._hex_to_rgb_triplet(primary)};")
        if secondary:
            root_lines.append(f"--bs-secondary: {secondary};")
            root_lines.append(
                f"--bs-secondary-rgb: {self._hex_to_rgb_triplet(secondary)};")
        if link:
            root_lines.append(f"--bs-link-color: {link};")

        if navbar_bg:
            navbar_lines.append(f"background: {navbar_bg} !important;")
        if navbar_text:
            navbar_lines.append(f"--NavBar-entry-color: {navbar_text};")

        css_blocks = []
        if root_lines:
            css_blocks.append(":root {" + "".join(root_lines) + "}")
        if navbar_lines:
            css_blocks.append(".o_main_navbar {" + "".join(navbar_lines) + "}")
        return "".join(css_blocks)
