from . import test_portal_phase0
from . import test_inbound_feed_service
from . import test_smoke
from . import test_prop_d1_double_booking
from . import test_prop_d4_company_consistency
from . import test_prop_d7_currency_resolution
from . import test_prop_d8_booking_reference_default
from . import test_prop_d9_sale_contract_reference_default
from . import test_prop_d10_rent_contract_reference_default
