# -*- coding: utf-8 -*-
"""
Transaction Monitoring Engine

Configurable rules to detect:
  - Cash transactions exceeding AED 55,000 (CBUAE threshold)
  - Structuring (splitting to avoid thresholds)
  - Rapid-fire transactions (velocity checks)
  - Round-amount transactions
  - High-value property transactions
  - Unusual patterns for customer profile

Each rule triggers an alert for AML officer review.
"""

from odoo import api, fields, models, _
from odoo.exceptions import UserError
from datetime import timedelta
import logging

_logger = logging.getLogger(__name__)


class TransactionMonitoringRule(models.Model):
    """Configurable transaction monitoring rule"""

    _name = 'aml.monitoring.rule'
    _description = 'Transaction Monitoring Rule'
    _order = 'sequence, name'
    _rec_name = 'name'

    name = fields.Char(string='Rule Name', required=True, translate=True)
    code = fields.Char(string='Rule Code', required=True, index=True)
    description = fields.Text(string='Description')
    active = fields.Boolean(default=True)
    sequence = fields.Integer(default=10)

    rule_type = fields.Selection([
        ('threshold', 'Amount Threshold'),
        ('velocity', 'Transaction Velocity'),
        ('structuring', 'Structuring Detection'),
        ('round_amount', 'Round Amount Detection'),
        ('pattern', 'Pattern Anomaly'),
    ], string='Rule Type', required=True, default='threshold')

    # --- Threshold parameters ---
    threshold_amount = fields.Float(
        string='Threshold Amount (AED)',
        help='Amount at which this rule triggers',
    )

    # --- Velocity parameters ---
    velocity_count = fields.Integer(
        string='Transaction Count',
        help='Number of transactions within the time window',
    )

    velocity_window_days = fields.Integer(
        string='Time Window (Days)',
        help='Number of days for the velocity check',
        default=30,
    )

    # --- Structuring parameters ---
    structuring_percentage = fields.Float(
        string='Structuring % Below Threshold',
        help='Flag if amount is within this % below the threshold',
        default=20.0,
    )

    # --- Scope ---
    applies_to = fields.Selection([
        ('all', 'All Transactions'),
        ('cash', 'Cash Only'),
        ('wire', 'Wire Transfers'),
        ('property', 'Property Transactions'),
    ], string='Applies To', default='all')

    severity = fields.Selection([
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    ], string='Severity', default='medium', required=True)

    auto_create_str = fields.Boolean(
        string='Auto-Create STR Draft',
        help='Automatically create a draft STR when this rule triggers',
    )

    alert_ids = fields.One2many(
        'aml.transaction.alert',
        'rule_id',
        string='Alerts',
    )

    alert_count = fields.Integer(
        string='# Alerts',
        compute='_compute_alert_count',
    )

    def _compute_alert_count(self):
        for rec in self:
            rec.alert_count = self.env['aml.transaction.alert'].search_count([
                ('rule_id', '=', rec.id),
            ])


class TransactionAlert(models.Model):
    """Alert generated by transaction monitoring rules"""

    _name = 'aml.transaction.alert'
    _description = 'Transaction Monitoring Alert'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _rec_name = 'name'
    _order = 'alert_date desc'

    name = fields.Char(
        string='Alert Reference',
        required=True,
        readonly=True,
        default='New',
        copy=False,
    )

    state = fields.Selection([
        ('new', 'New'),
        ('investigating', 'Under Investigation'),
        ('escalated', 'Escalated'),
        ('false_positive', 'False Positive'),
        ('closed', 'Closed — No Action'),
        ('str_filed', 'STR Filed'),
    ], string='Status', default='new', tracking=True, index=True)

    rule_id = fields.Many2one(
        'aml.monitoring.rule',
        string='Triggered Rule',
        required=True,
        ondelete='restrict',
    )

    severity = fields.Selection(
        related='rule_id.severity',
        string='Severity',
        store=True,
        readonly=True,
    )

    alert_date = fields.Datetime(
        string='Alert Date',
        default=fields.Datetime.now,
        required=True,
    )

    partner_id = fields.Many2one(
        'res.partner',
        string='Customer',
        required=True,
        ondelete='restrict',
        tracking=True,
    )

    # --- Transaction context ---
    transaction_amount = fields.Monetary(
        string='Transaction Amount (AED)',
        currency_field='currency_id',
    )

    currency_id = fields.Many2one(
        'res.currency',
        default=lambda self: self.env.company.currency_id,
    )

    invoice_id = fields.Many2one(
        'account.move',
        string='Related Invoice',
        ondelete='set null',
    )

    transaction_date = fields.Date(string='Transaction Date')

    alert_description = fields.Text(
        string='Alert Description',
        help='Auto-generated description of why this alert was raised',
    )

    # --- Investigation ---
    assigned_to_id = fields.Many2one(
        'res.users',
        string='Assigned To',
        tracking=True,
    )

    investigation_notes = fields.Text(
        string='Investigation Notes',
    )

    resolution_date = fields.Datetime(
        string='Resolution Date',
    )

    # --- Links ---
    goaml_report_id = fields.Many2one(
        'aml.goaml.report',
        string='Related goAML Report',
        ondelete='set null',
    )

    risk_assessment_id = fields.Many2one(
        'aml.risk.assessment',
        string='Risk Assessment',
        ondelete='set null',
    )

    company_id = fields.Many2one(
        'res.company',
        default=lambda self: self.env.company,
        required=True,
    )

    case_id = fields.Many2one(
        'aml.investigation.case',
        string='Investigation Case',
        ondelete='set null',
        index=True,
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', 'New') == 'New':
                vals['name'] = self.env['ir.sequence'].next_by_code(
                    'aml.transaction.alert'
                ) or 'New'
        return super().create(vals_list)

    # -------------------------------------------------------
    # WORKFLOW
    # -------------------------------------------------------

    def action_investigate(self):
        for rec in self:
            rec.write({
                'state': 'investigating',
                'assigned_to_id': rec.assigned_to_id.id or self.env.uid,
            })

    def action_escalate(self):
        for rec in self:
            rec.write({'state': 'escalated'})
            rec.message_post(
                body=_('Alert escalated for MLRO review.'),
                message_type='notification',
                subtype_xmlid='mail.mt_note',
            )

    def action_false_positive(self):
        for rec in self:
            if not rec.investigation_notes:
                raise UserError(_('Investigation notes are required to mark as false positive.'))
            rec.write({
                'state': 'false_positive',
                'resolution_date': fields.Datetime.now(),
            })

    def action_close(self):
        for rec in self:
            rec.write({
                'state': 'closed',
                'resolution_date': fields.Datetime.now(),
            })

    def action_create_str(self):
        """Create a draft STR from this alert"""
        self.ensure_one()
        report = self.env['aml.goaml.report'].create({
            'report_type': 'str',
            'partner_id': self.partner_id.id,
            'transaction_date': self.transaction_date,
            'transaction_amount': self.transaction_amount,
            'reason_for_suspicion': _(
                'Auto-generated from alert %s.\nRule: %s\n\n%s',
                self.name, self.rule_id.name, self.alert_description or '',
            ),
        })
        self.write({
            'state': 'escalated',
            'goaml_report_id': report.id,
            'resolution_date': False,
        })
        self.message_post(
            body=_('Draft STR created: %s. Continue MLRO workflow until FIU filing is complete.', report.name),
            message_type='notification',
            subtype_xmlid='mail.mt_note',
        )
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'aml.goaml.report',
            'res_id': report.id,
            'view_mode': 'form',
            'target': 'current',
        }

    # -------------------------------------------------------
    # MONITORING ENGINE
    # -------------------------------------------------------

    @api.model
    def run_transaction_monitoring(self):
        """Scheduled action: scan posted invoices against monitoring rules.
        Called by ir.cron daily.
        """
        _logger.info('AML Transaction Monitoring: starting scan...')
        rules = self.env['aml.monitoring.rule'].search([('active', '=', True)])
        if not rules:
            _logger.info('No active monitoring rules found.')
            return

        # Scan invoices posted in last 24h (or broader if needed)
        yesterday = fields.Datetime.now() - timedelta(days=1)
        invoices = self.env['account.move'].search([
            ('state', '=', 'posted'),
            ('move_type', 'in', ['out_invoice', 'out_refund']),
            ('write_date', '>=', yesterday),
        ])

        alert_count = 0
        for rule in rules:
            if rule.rule_type == 'threshold':
                alert_count += self._check_threshold_rule(rule, invoices)
            elif rule.rule_type == 'velocity':
                alert_count += self._check_velocity_rule(rule, invoices)
            elif rule.rule_type == 'structuring':
                alert_count += self._check_structuring_rule(rule, invoices)
            elif rule.rule_type == 'round_amount':
                alert_count += self._check_round_amount_rule(rule, invoices)

        _logger.info('AML Transaction Monitoring: %d alerts generated.', alert_count)
        return alert_count

    def _check_threshold_rule(self, rule, invoices):
        """Check if any invoice exceeds the threshold amount"""
        count = 0
        for inv in invoices:
            if inv.amount_total >= rule.threshold_amount:
                existing = self.search_count([
                    ('rule_id', '=', rule.id),
                    ('invoice_id', '=', inv.id),
                ])
                if not existing:
                    self._create_alert(rule, inv, _(
                        'Transaction amount AED %s exceeds threshold AED %s.',
                        f'{inv.amount_total:,.2f}',
                        f'{rule.threshold_amount:,.2f}',
                    ))
                    count += 1
        return count

    def _check_velocity_rule(self, rule, invoices):
        """Check transaction frequency per partner"""
        count = 0
        partners = invoices.mapped('partner_id')
        window_start = fields.Date.today() - timedelta(days=rule.velocity_window_days)
        for partner in partners:
            txn_count = self.env['account.move'].search_count([
                ('partner_id', '=', partner.id),
                ('state', '=', 'posted'),
                ('move_type', 'in', ['out_invoice', 'out_refund']),
                ('invoice_date', '>=', window_start),
            ])
            if txn_count >= rule.velocity_count:
                existing = self.search_count([
                    ('rule_id', '=', rule.id),
                    ('partner_id', '=', partner.id),
                    ('alert_date', '>=', fields.Datetime.to_string(
                        fields.Datetime.now() - timedelta(days=rule.velocity_window_days)
                    )),
                ])
                if not existing:
                    self._create_alert_no_invoice(rule, partner, _(
                        '%d transactions in %d days (threshold: %d).',
                        txn_count, rule.velocity_window_days, rule.velocity_count,
                    ))
                    count += 1
        return count

    def _check_structuring_rule(self, rule, invoices):
        """Detect potential structuring — amounts just below threshold"""
        count = 0
        threshold = rule.threshold_amount or 55000.0
        floor = threshold * (1 - rule.structuring_percentage / 100.0)
        for inv in invoices:
            if floor <= inv.amount_total < threshold:
                existing = self.search_count([
                    ('rule_id', '=', rule.id),
                    ('invoice_id', '=', inv.id),
                ])
                if not existing:
                    self._create_alert(rule, inv, _(
                        'Potential structuring: AED %s is within %s%% of threshold AED %s.',
                        f'{inv.amount_total:,.2f}',
                        f'{rule.structuring_percentage:.0f}',
                        f'{threshold:,.2f}',
                    ))
                    count += 1
        return count

    def _check_round_amount_rule(self, rule, invoices):
        """Detect suspiciously round amounts"""
        count = 0
        threshold = rule.threshold_amount or 10000.0
        for inv in invoices:
            if inv.amount_total >= threshold and inv.amount_total % 1000 == 0:
                existing = self.search_count([
                    ('rule_id', '=', rule.id),
                    ('invoice_id', '=', inv.id),
                ])
                if not existing:
                    self._create_alert(rule, inv, _(
                        'Round amount AED %s detected (multiple of 1,000).',
                        f'{inv.amount_total:,.2f}',
                    ))
                    count += 1
        return count

    def _create_alert(self, rule, invoice, description):
        """Helper: create alert linked to an invoice"""
        vals = {
            'rule_id': rule.id,
            'partner_id': invoice.partner_id.id,
            'transaction_amount': invoice.amount_total,
            'invoice_id': invoice.id,
            'transaction_date': invoice.invoice_date,
            'alert_description': description,
        }
        alert = self.create(vals)
        if rule.auto_create_str:
            alert.action_create_str()
        return alert

    def _create_alert_no_invoice(self, rule, partner, description):
        """Helper: create alert without specific invoice"""
        vals = {
            'rule_id': rule.id,
            'partner_id': partner.id,
            'alert_description': description,
        }
        return self.create(vals)
